---

name: Build

on:
  push:
    branches:
      - 'main'

jobs:

  build-image:
    name: Build Container Image
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    
      - id: commit
        uses: prompt/actions-commit-hash@v3
        with:
          prefix: ""
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tlsdemo:${{ steps.commit.outputs.short }}
