# comments

---

name: Tag

on:
  push:
    tags:
      - 'production-v*'

jobs:

  push_to_registry:

    name:        Push Docker image to Docker Hub
    runs-on:     ubuntu-latest
    permissions: write-all

    steps:

      - name: checkout_repository
        id:   checkout_repository
        uses: actions/checkout@v4

      - name: fetch_tags
        id:   fetch_tags
        run:  git fetch --tags --force

      - name: display_tag_name
        id:   display_tag_name
        run:  echo "${{ github.ref_name }}"

      - name: find_commit_hash
        id:   find_commit_hash
        run:  echo "COMMIT_HASH=$(git rev-list -n 1 ${{ github.ref_name }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: set_tag
        id:   set_tag
        run:  git tag  -f        production ${{ steps.find_commit_hash.outputs.COMMIT_HASH }}
              git push -f origin production
